---
- name: Installing Tool Installer
  hosts: all
  gather_facts: false

  tasks:
    - name: Download the Apache installer
      win_get_url:
        url: https://dl-agent.pstmn.io/download/latest/win64
        dest: D:\Downloads\Postman-Agent-win64-0.4.17-Setup.exe


    - name: Install MSI
      win_package:
        path: D:\Downloads\Postman-Agent-win64-0.4.17-Setup.exe
        state: present
        reboot: no

    - name: Install MSI 2
      win_package: 
        path: D:\Downloads\Postman-Agent-win64-0.4.17-Setup.exe
        arguments:
          - /install
          - /passive
          - /norestart
