---
- name: UnInstalling Apache MSI
  hosts: all
  gather_facts: false
  tasks:
    - name: UnInstall MSI
      win_package:
        path: D:\Downloads\httpd-2.2.25-win32-x86-no_ssl.msi
        state: absent
